FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential libpcap-dev libpcre3-dev \
    libdumbnet-dev bison flex zlib1g-dev \
    liblzma-dev openssl libssl-dev wget libtirpc-dev \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://www.snort.org/downloads/snort/daq-2.0.7.tar.gz && \
    tar -xzf daq-2.0.7.tar.gz && \
    cd daq-2.0.7 && ./configure && make && make install && \
    ldconfig

RUN wget https://www.snort.org/downloads/snort/snort-2.9.20.tar.gz && \
    tar -xzf snort-2.9.20.tar.gz && \
    cd snort-2.9.20 && \
    ./configure --enable-non-ether-decoder --disable-open-appid \
        CPPFLAGS="-I/usr/include/tirpc" LDFLAGS="-ltirpc" && \
    make && make install && ldconfig

RUN mkdir -p /etc/snort/rules /var/log/snort

RUN cp /snort-2.9.20/etc/*.conf /snort-2.9.20/etc/*.config /snort-2.9.20/etc/*.map /etc/snort/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]